### ISSUE TITLE
About Experimental results

### ISSUE THREAD

**Issue by chujunc** [efeslab/moesi-prime#1]
Dear author,
  I am trying to analyse the difference between non-inclusive llc (last level cache) and inclusive llc, do you know which stats (like l1cache hit rate, l2 cache hit rate or some else?) in m5out/stats.txt are helpful, and which of the 13 benchmarks in parsec2.1 should be selected?

Best regards,
Charles

**Comment by kevinloughlin** [comment]
Hi Charles,

The specific relevant stats will depend on the protocol that you use; the protocol will also affect the clusivity of the LLC. We only ran non-inclusive protocols in the [paper](https://www.kevinloughlin.org/moesi-prime.pdf), as shown in Table 1. The non-inclusivity is baked into the protocols' ruby subsystem implementations and is non-trivial to change; for example, please see [the L2 implementation](https://github.com/efeslab/moesi-prime/blob/main/src/mem/ruby/protocol/MOESI-prime-L2cache.sm) (where the L2 is the LLC in this protocol). Broadly-speaking, stats ending with "demand_hits" and "demand_misses" are likely most relevant.

For MOESI-prime, we used 12/13 benchmarks in PARSEC 3.0; please see section 6 for more detail.

Hope this helps, and best wishes,

Kevin
